version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bookrental-sqlserver
    environment:
      SA_PASSWORD: "Miran@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      retries: 10
      start_period: 20s

  bookrental-api:
    build: 
      context: .
      dockerfile: BookRental/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=BookRentalDb;User Id=sa;Password=Miran@123;TrustServerCertificate=True;
    networks:
      - app-network

  frontend:
    build: ./BookRentalUI/book-rental-ui
    ports:
      - "3000:80"
    depends_on:
      - bookrental-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
